WITH tree_map AS (
    SELECT
        t1.id,
        t1.p_id,
        t2.id AS c_id
    FROM Tree t1
    LEFT JOIN Tree t2
        ON t1.id = t2.p_id
)

SELECT
    DISTINCT id,
    CASE
        WHEN p_id IS NULL AND c_id IS NOT NULL THEN 'Root'
        WHEN p_id IS NOT NULL AND c_id IS NOT NULL THEN 'Inner'
        WHEN p_id IS NOT NULL AND c_ID IS NULL THEN 'Leaf'
        ELSE 'Root'
    END AS type
FROM tree_map
